// Package redispartition exposes precomputed string tags whose CRC16 hash
// slots distribute evenly across Redis Cluster nodes for any cluster size
// up to the configured number of partitions. Tags are used as Redis Cluster
// hash tags so that PUB/SUB partitions and their associated keys land on
// well-spread slots.
//
// Tag tables are deterministic for a given partition count and are
// regenerated by cmd/precompute. Runtime callers use FindTags to look up
// the table for a configured partition count.
package redispartition

const totalSlots = 16384

// FindTags returns the precomputed tags for numPartitions. The returned
// slice is shared with the package-level table and MUST NOT be mutated by
// the caller. An error is returned if numPartitions is not one of the
// precomputed sizes; use PrecomputedSizes to discover them.
func FindTags(numPartitions int) ([]string, error) { _ = "STUB: not implemented"; return nil, nil }

// PrecomputedSizes returns the sorted list of partition counts for which
// precomputed tags are bundled.
func PrecomputedSizes() []int { _ = "STUB: not implemented"; return nil }

// SlotToNode returns which node (0-based) owns a given slot in a cluster
// of the given size. This matches Redis Cluster's contiguous slot
// assignment (sn = totalSlots / numNodes, with the first totalSlots %
// numNodes nodes getting one extra slot).
func SlotToNode(slot, numNodes int) int { _ = "STUB: not implemented"; return 0 }

// TagSlot returns the Redis hash slot for a given tag string.
func TagSlot(tag string) int { _ = "STUB: not implemented"; return 0 }

// crc16 computes CRC-CCITT (XModem) matching Redis's CRC16.
func crc16(data []byte) uint16 { _ = "STUB: not implemented"; return 0 }
