// Install protoc compiler https://github.com/google/protobuf/releases
// Install gogofaster program:
// go get -u github.com/gogo/protobuf/protoc-gen-gogofaster
// protoc --proto_path=../../vendor:. --gogofaster_out=. control.proto
// Note that we use vendored gogoprotobuf path in example above.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: control.proto

package controlpb

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Uid   string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// 2,3 removed.
	Node           *Node           `protobuf:"bytes,4,opt,name=node,proto3" json:"node,omitempty"`
	Unsubscribe    *Unsubscribe    `protobuf:"bytes,5,opt,name=unsubscribe,proto3" json:"unsubscribe,omitempty"`
	Disconnect     *Disconnect     `protobuf:"bytes,6,opt,name=disconnect,proto3" json:"disconnect,omitempty"`
	Shutdown       *Shutdown       `protobuf:"bytes,7,opt,name=shutdown,proto3" json:"shutdown,omitempty"`
	SurveyRequest  *SurveyRequest  `protobuf:"bytes,8,opt,name=survey_request,json=surveyRequest,proto3" json:"survey_request,omitempty"`
	SurveyResponse *SurveyResponse `protobuf:"bytes,9,opt,name=survey_response,json=surveyResponse,proto3" json:"survey_response,omitempty"`
	Subscribe      *Subscribe      `protobuf:"bytes,10,opt,name=subscribe,proto3" json:"subscribe,omitempty"`
	Notification   *Notification   `protobuf:"bytes,11,opt,name=notification,proto3" json:"notification,omitempty"`
	Refresh        *Refresh        `protobuf:"bytes,12,opt,name=refresh,proto3" json:"refresh,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Command) Reset() { _ = "STUB: not implemented"; return }

func (x *Command) String() string { _ = "STUB: not implemented"; return "" }

func (*Command) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Command) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Command) GetUid() string { _ = "STUB: not implemented"; return "" }

func (x *Command) GetNode() *Node { _ = "STUB: not implemented"; return nil }

func (x *Command) GetUnsubscribe() *Unsubscribe { _ = "STUB: not implemented"; return nil }

func (x *Command) GetDisconnect() *Disconnect { _ = "STUB: not implemented"; return nil }

func (x *Command) GetShutdown() *Shutdown { _ = "STUB: not implemented"; return nil }

func (x *Command) GetSurveyRequest() *SurveyRequest { _ = "STUB: not implemented"; return nil }

func (x *Command) GetSurveyResponse() *SurveyResponse { _ = "STUB: not implemented"; return nil }

func (x *Command) GetSubscribe() *Subscribe { _ = "STUB: not implemented"; return nil }

func (x *Command) GetNotification() *Notification { _ = "STUB: not implemented"; return nil }

func (x *Command) GetRefresh() *Refresh { _ = "STUB: not implemented"; return nil }

type Shutdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shutdown) Reset() { _ = "STUB: not implemented"; return }

func (x *Shutdown) String() string { _ = "STUB: not implemented"; return "" }

func (*Shutdown) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Shutdown) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Shutdown.ProtoReflect.Descriptor instead.
func (*Shutdown) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	NumClients    uint32                 `protobuf:"varint,4,opt,name=num_clients,json=numClients,proto3" json:"num_clients,omitempty"`
	NumUsers      uint32                 `protobuf:"varint,5,opt,name=num_users,json=numUsers,proto3" json:"num_users,omitempty"`
	NumChannels   uint32                 `protobuf:"varint,6,opt,name=num_channels,json=numChannels,proto3" json:"num_channels,omitempty"`
	Uptime        uint32                 `protobuf:"varint,7,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Metrics       *Metrics               `protobuf:"bytes,8,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Data          []byte                 `protobuf:"bytes,9,opt,name=data,proto3" json:"data,omitempty"`
	NumSubs       uint32                 `protobuf:"varint,10,opt,name=num_subs,json=numSubs,proto3" json:"num_subs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() { _ = "STUB: not implemented"; return }

func (x *Node) String() string { _ = "STUB: not implemented"; return "" }

func (*Node) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Node) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Node) GetUid() string { _ = "STUB: not implemented"; return "" }

func (x *Node) GetName() string { _ = "STUB: not implemented"; return "" }

func (x *Node) GetVersion() string { _ = "STUB: not implemented"; return "" }

func (x *Node) GetNumClients() uint32 { _ = "STUB: not implemented"; return 0 }

func (x *Node) GetNumUsers() uint32 { _ = "STUB: not implemented"; return 0 }

func (x *Node) GetNumChannels() uint32 { _ = "STUB: not implemented"; return 0 }

func (x *Node) GetUptime() uint32 { _ = "STUB: not implemented"; return 0 }

func (x *Node) GetMetrics() *Metrics { _ = "STUB: not implemented"; return nil }

func (x *Node) GetData() []byte { _ = "STUB: not implemented"; return nil }

func (x *Node) GetNumSubs() uint32 { _ = "STUB: not implemented"; return 0 }

type Metrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interval      float64                `protobuf:"fixed64,1,opt,name=interval,proto3" json:"interval,omitempty"`
	Items         map[string]float64     `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics) Reset() { _ = "STUB: not implemented"; return }

func (x *Metrics) String() string { _ = "STUB: not implemented"; return "" }

func (*Metrics) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Metrics) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Metrics) GetInterval() float64 { _ = "STUB: not implemented"; return 0 }

func (x *Metrics) GetItems() map[string]float64 { _ = "STUB: not implemented"; return nil }

type Subscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	EmitPresence  bool                   `protobuf:"varint,3,opt,name=emit_presence,json=emitPresence,proto3" json:"emit_presence,omitempty"`
	EmitJoinLeave bool                   `protobuf:"varint,4,opt,name=emit_join_leave,json=emitJoinLeave,proto3" json:"emit_join_leave,omitempty"`
	ExpireAt      int64                  `protobuf:"varint,5,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	Position      bool                   `protobuf:"varint,6,opt,name=position,proto3" json:"position,omitempty"`
	Recover       bool                   `protobuf:"varint,7,opt,name=recover,proto3" json:"recover,omitempty"`
	ChannelInfo   []byte                 `protobuf:"bytes,8,opt,name=channel_info,json=channelInfo,proto3" json:"channel_info,omitempty"`
	Client        string                 `protobuf:"bytes,9,opt,name=client,proto3" json:"client,omitempty"`
	Data          []byte                 `protobuf:"bytes,10,opt,name=data,proto3" json:"data,omitempty"`
	RecoverSince  *StreamPosition        `protobuf:"bytes,11,opt,name=recover_since,json=recoverSince,proto3" json:"recover_since,omitempty"`
	Session       string                 `protobuf:"bytes,12,opt,name=session,proto3" json:"session,omitempty"`
	PushJoinLeave bool                   `protobuf:"varint,13,opt,name=push_join_leave,json=pushJoinLeave,proto3" json:"push_join_leave,omitempty"`
	Source        uint32                 `protobuf:"varint,14,opt,name=source,proto3" json:"source,omitempty"`
	LabelFilter   *FilterNode            `protobuf:"bytes,15,opt,name=label_filter,json=labelFilter,proto3" json:"label_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscribe) Reset() { _ = "STUB: not implemented"; return }

func (x *Subscribe) String() string { _ = "STUB: not implemented"; return "" }

func (*Subscribe) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Subscribe) GetUser() string { _ = "STUB: not implemented"; return "" }

func (x *Subscribe) GetChannel() string { _ = "STUB: not implemented"; return "" }

func (x *Subscribe) GetEmitPresence() bool { _ = "STUB: not implemented"; return false }

func (x *Subscribe) GetEmitJoinLeave() bool { _ = "STUB: not implemented"; return false }

func (x *Subscribe) GetExpireAt() int64 { _ = "STUB: not implemented"; return 0 }

func (x *Subscribe) GetPosition() bool { _ = "STUB: not implemented"; return false }

func (x *Subscribe) GetRecover() bool { _ = "STUB: not implemented"; return false }

func (x *Subscribe) GetChannelInfo() []byte { _ = "STUB: not implemented"; return nil }

func (x *Subscribe) GetClient() string { _ = "STUB: not implemented"; return "" }

func (x *Subscribe) GetData() []byte { _ = "STUB: not implemented"; return nil }

func (x *Subscribe) GetRecoverSince() *StreamPosition { _ = "STUB: not implemented"; return nil }

func (x *Subscribe) GetSession() string { _ = "STUB: not implemented"; return "" }

func (x *Subscribe) GetPushJoinLeave() bool { _ = "STUB: not implemented"; return false }

func (x *Subscribe) GetSource() uint32 { _ = "STUB: not implemented"; return 0 }

func (x *Subscribe) GetLabelFilter() *FilterNode { _ = "STUB: not implemented"; return nil }

type StreamPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Epoch         string                 `protobuf:"bytes,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPosition) Reset() { _ = "STUB: not implemented"; return }

func (x *StreamPosition) String() string { _ = "STUB: not implemented"; return "" }

func (*StreamPosition) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *StreamPosition) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use StreamPosition.ProtoReflect.Descriptor instead.
func (*StreamPosition) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *StreamPosition) GetOffset() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *StreamPosition) GetEpoch() string { _ = "STUB: not implemented"; return "" }

// FilterNode is the wire-compatible mirror of centrifugal/protocol FilterNode.
// Kept here to avoid a cross-module proto import; converted at the pub/dispatch
// boundary. Field numbers and types must match protocol.FilterNode exactly.
type FilterNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            string                 `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Cmp           string                 `protobuf:"bytes,3,opt,name=cmp,proto3" json:"cmp,omitempty"`
	Val           string                 `protobuf:"bytes,4,opt,name=val,proto3" json:"val,omitempty"`
	Vals          []string               `protobuf:"bytes,5,rep,name=vals,proto3" json:"vals,omitempty"`
	Nodes         []*FilterNode          `protobuf:"bytes,6,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterNode) Reset() { _ = "STUB: not implemented"; return }

func (x *FilterNode) String() string { _ = "STUB: not implemented"; return "" }

func (*FilterNode) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *FilterNode) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use FilterNode.ProtoReflect.Descriptor instead.
func (*FilterNode) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *FilterNode) GetOp() string { _ = "STUB: not implemented"; return "" }

func (x *FilterNode) GetKey() string { _ = "STUB: not implemented"; return "" }

func (x *FilterNode) GetCmp() string { _ = "STUB: not implemented"; return "" }

func (x *FilterNode) GetVal() string { _ = "STUB: not implemented"; return "" }

func (x *FilterNode) GetVals() []string { _ = "STUB: not implemented"; return nil }

func (x *FilterNode) GetNodes() []*FilterNode { _ = "STUB: not implemented"; return nil }

type Unsubscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Client        string                 `protobuf:"bytes,3,opt,name=client,proto3" json:"client,omitempty"`
	Session       string                 `protobuf:"bytes,4,opt,name=session,proto3" json:"session,omitempty"`
	Code          uint32                 `protobuf:"varint,5,opt,name=code,proto3" json:"code,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	LabelFilter   *FilterNode            `protobuf:"bytes,7,opt,name=label_filter,json=labelFilter,proto3" json:"label_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unsubscribe) Reset() { _ = "STUB: not implemented"; return }

func (x *Unsubscribe) String() string { _ = "STUB: not implemented"; return "" }

func (*Unsubscribe) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Unsubscribe) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Unsubscribe.ProtoReflect.Descriptor instead.
func (*Unsubscribe) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Unsubscribe) GetChannel() string { _ = "STUB: not implemented"; return "" }

func (x *Unsubscribe) GetUser() string { _ = "STUB: not implemented"; return "" }

func (x *Unsubscribe) GetClient() string { _ = "STUB: not implemented"; return "" }

func (x *Unsubscribe) GetSession() string { _ = "STUB: not implemented"; return "" }

func (x *Unsubscribe) GetCode() uint32 { _ = "STUB: not implemented"; return 0 }

func (x *Unsubscribe) GetReason() string { _ = "STUB: not implemented"; return "" }

func (x *Unsubscribe) GetLabelFilter() *FilterNode { _ = "STUB: not implemented"; return nil }

type Disconnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Whitelist     []string               `protobuf:"bytes,2,rep,name=whitelist,proto3" json:"whitelist,omitempty"`
	Code          uint32                 `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Reconnect     bool                   `protobuf:"varint,5,opt,name=reconnect,proto3" json:"reconnect,omitempty"`
	Client        string                 `protobuf:"bytes,6,opt,name=client,proto3" json:"client,omitempty"`
	Session       string                 `protobuf:"bytes,7,opt,name=session,proto3" json:"session,omitempty"`
	LabelFilter   *FilterNode            `protobuf:"bytes,8,opt,name=label_filter,json=labelFilter,proto3" json:"label_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disconnect) Reset() { _ = "STUB: not implemented"; return }

func (x *Disconnect) String() string { _ = "STUB: not implemented"; return "" }

func (*Disconnect) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Disconnect) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Disconnect.ProtoReflect.Descriptor instead.
func (*Disconnect) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Disconnect) GetUser() string { _ = "STUB: not implemented"; return "" }

func (x *Disconnect) GetWhitelist() []string { _ = "STUB: not implemented"; return nil }

func (x *Disconnect) GetCode() uint32 { _ = "STUB: not implemented"; return 0 }

func (x *Disconnect) GetReason() string { _ = "STUB: not implemented"; return "" }

func (x *Disconnect) GetReconnect() bool { _ = "STUB: not implemented"; return false }

func (x *Disconnect) GetClient() string { _ = "STUB: not implemented"; return "" }

func (x *Disconnect) GetSession() string { _ = "STUB: not implemented"; return "" }

func (x *Disconnect) GetLabelFilter() *FilterNode { _ = "STUB: not implemented"; return nil }

type SurveyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Op            string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SurveyRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *SurveyRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*SurveyRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *SurveyRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use SurveyRequest.ProtoReflect.Descriptor instead.
func (*SurveyRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *SurveyRequest) GetId() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *SurveyRequest) GetOp() string { _ = "STUB: not implemented"; return "" }

func (x *SurveyRequest) GetData() []byte { _ = "STUB: not implemented"; return nil }

type SurveyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          uint32                 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SurveyResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *SurveyResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*SurveyResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *SurveyResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use SurveyResponse.ProtoReflect.Descriptor instead.
func (*SurveyResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *SurveyResponse) GetId() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *SurveyResponse) GetCode() uint32 { _ = "STUB: not implemented"; return 0 }

func (x *SurveyResponse) GetData() []byte { _ = "STUB: not implemented"; return nil }

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            string                 `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() { _ = "STUB: not implemented"; return }

func (x *Notification) String() string { _ = "STUB: not implemented"; return "" }

func (*Notification) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Notification) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Notification) GetOp() string { _ = "STUB: not implemented"; return "" }

func (x *Notification) GetData() []byte { _ = "STUB: not implemented"; return nil }

type Refresh struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Client        string                 `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	Expired       bool                   `protobuf:"varint,3,opt,name=expired,proto3" json:"expired,omitempty"`
	ExpireAt      int64                  `protobuf:"varint,4,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	Info          []byte                 `protobuf:"bytes,5,opt,name=info,proto3" json:"info,omitempty"`
	Session       string                 `protobuf:"bytes,6,opt,name=session,proto3" json:"session,omitempty"`
	LabelFilter   *FilterNode            `protobuf:"bytes,7,opt,name=label_filter,json=labelFilter,proto3" json:"label_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Refresh) Reset() { _ = "STUB: not implemented"; return }

func (x *Refresh) String() string { _ = "STUB: not implemented"; return "" }

func (*Refresh) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Refresh) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Refresh.ProtoReflect.Descriptor instead.
func (*Refresh) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Refresh) GetUser() string { _ = "STUB: not implemented"; return "" }

func (x *Refresh) GetClient() string { _ = "STUB: not implemented"; return "" }

func (x *Refresh) GetExpired() bool { _ = "STUB: not implemented"; return false }

func (x *Refresh) GetExpireAt() int64 { _ = "STUB: not implemented"; return 0 }

func (x *Refresh) GetInfo() []byte { _ = "STUB: not implemented"; return nil }

func (x *Refresh) GetSession() string { _ = "STUB: not implemented"; return "" }

func (x *Refresh) GetLabelFilter() *FilterNode { _ = "STUB: not implemented"; return nil }

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\tcontrolpb\"\x86\x04\n" +
	"\aCommand\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12#\n" +
	"\x04node\x18\x04 \x01(\v2\x0f.controlpb.NodeR\x04node\x128\n" +
	"\vunsubscribe\x18\x05 \x01(\v2\x16.controlpb.UnsubscribeR\vunsubscribe\x125\n" +
	"\n" +
	"disconnect\x18\x06 \x01(\v2\x15.controlpb.DisconnectR\n" +
	"disconnect\x12/\n" +
	"\bshutdown\x18\a \x01(\v2\x13.controlpb.ShutdownR\bshutdown\x12?\n" +
	"\x0esurvey_request\x18\b \x01(\v2\x18.controlpb.SurveyRequestR\rsurveyRequest\x12B\n" +
	"\x0fsurvey_response\x18\t \x01(\v2\x19.controlpb.SurveyResponseR\x0esurveyResponse\x122\n" +
	"\tsubscribe\x18\n" +
	" \x01(\v2\x14.controlpb.SubscribeR\tsubscribe\x12;\n" +
	"\fnotification\x18\v \x01(\v2\x17.controlpb.NotificationR\fnotification\x12,\n" +
	"\arefresh\x18\f \x01(\v2\x12.controlpb.RefreshR\arefresh\"\n" +
	"\n" +
	"\bShutdown\"\x9c\x02\n" +
	"\x04Node\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1f\n" +
	"\vnum_clients\x18\x04 \x01(\rR\n" +
	"numClients\x12\x1b\n" +
	"\tnum_users\x18\x05 \x01(\rR\bnumUsers\x12!\n" +
	"\fnum_channels\x18\x06 \x01(\rR\vnumChannels\x12\x16\n" +
	"\x06uptime\x18\a \x01(\rR\x06uptime\x12,\n" +
	"\ametrics\x18\b \x01(\v2\x12.controlpb.MetricsR\ametrics\x12\x12\n" +
	"\x04data\x18\t \x01(\fR\x04data\x12\x19\n" +
	"\bnum_subs\x18\n" +
	" \x01(\rR\anumSubs\"\x94\x01\n" +
	"\aMetrics\x12\x1a\n" +
	"\binterval\x18\x01 \x01(\x01R\binterval\x123\n" +
	"\x05items\x18\x02 \x03(\v2\x1d.controlpb.Metrics.ItemsEntryR\x05items\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xfc\x03\n" +
	"\tSubscribe\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12#\n" +
	"\remit_presence\x18\x03 \x01(\bR\femitPresence\x12&\n" +
	"\x0femit_join_leave\x18\x04 \x01(\bR\remitJoinLeave\x12\x1b\n" +
	"\texpire_at\x18\x05 \x01(\x03R\bexpireAt\x12\x1a\n" +
	"\bposition\x18\x06 \x01(\bR\bposition\x12\x18\n" +
	"\arecover\x18\a \x01(\bR\arecover\x12!\n" +
	"\fchannel_info\x18\b \x01(\fR\vchannelInfo\x12\x16\n" +
	"\x06client\x18\t \x01(\tR\x06client\x12\x12\n" +
	"\x04data\x18\n" +
	" \x01(\fR\x04data\x12>\n" +
	"\rrecover_since\x18\v \x01(\v2\x19.controlpb.StreamPositionR\frecoverSince\x12\x18\n" +
	"\asession\x18\f \x01(\tR\asession\x12&\n" +
	"\x0fpush_join_leave\x18\r \x01(\bR\rpushJoinLeave\x12\x16\n" +
	"\x06source\x18\x0e \x01(\rR\x06source\x128\n" +
	"\flabel_filter\x18\x0f \x01(\v2\x15.controlpb.FilterNodeR\vlabelFilter\">\n" +
	"\x0eStreamPosition\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\tR\x05epoch\"\x93\x01\n" +
	"\n" +
	"FilterNode\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\tR\x02op\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x10\n" +
	"\x03cmp\x18\x03 \x01(\tR\x03cmp\x12\x10\n" +
	"\x03val\x18\x04 \x01(\tR\x03val\x12\x12\n" +
	"\x04vals\x18\x05 \x03(\tR\x04vals\x12+\n" +
	"\x05nodes\x18\x06 \x03(\v2\x15.controlpb.FilterNodeR\x05nodes\"\xd3\x01\n" +
	"\vUnsubscribe\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x16\n" +
	"\x06client\x18\x03 \x01(\tR\x06client\x12\x18\n" +
	"\asession\x18\x04 \x01(\tR\asession\x12\x12\n" +
	"\x04code\x18\x05 \x01(\rR\x04code\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x128\n" +
	"\flabel_filter\x18\a \x01(\v2\x15.controlpb.FilterNodeR\vlabelFilter\"\xf4\x01\n" +
	"\n" +
	"Disconnect\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x1c\n" +
	"\twhitelist\x18\x02 \x03(\tR\twhitelist\x12\x12\n" +
	"\x04code\x18\x03 \x01(\rR\x04code\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1c\n" +
	"\treconnect\x18\x05 \x01(\bR\treconnect\x12\x16\n" +
	"\x06client\x18\x06 \x01(\tR\x06client\x12\x18\n" +
	"\asession\x18\a \x01(\tR\asession\x128\n" +
	"\flabel_filter\x18\b \x01(\v2\x15.controlpb.FilterNodeR\vlabelFilter\"C\n" +
	"\rSurveyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"H\n" +
	"\x0eSurveyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\rR\x04code\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"2\n" +
	"\fNotification\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\tR\x02op\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xd4\x01\n" +
	"\aRefresh\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x16\n" +
	"\x06client\x18\x02 \x01(\tR\x06client\x12\x18\n" +
	"\aexpired\x18\x03 \x01(\bR\aexpired\x12\x1b\n" +
	"\texpire_at\x18\x04 \x01(\x03R\bexpireAt\x12\x12\n" +
	"\x04info\x18\x05 \x01(\fR\x04info\x12\x18\n" +
	"\asession\x18\x06 \x01(\tR\asession\x128\n" +
	"\flabel_filter\x18\a \x01(\v2\x15.controlpb.FilterNodeR\vlabelFilterB\x0eZ\f./;controlpbb\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte { _ = "STUB: not implemented"; return nil }

var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_control_proto_goTypes = []any{
	(*Command)(nil),        // 0: controlpb.Command
	(*Shutdown)(nil),       // 1: controlpb.Shutdown
	(*Node)(nil),           // 2: controlpb.Node
	(*Metrics)(nil),        // 3: controlpb.Metrics
	(*Subscribe)(nil),      // 4: controlpb.Subscribe
	(*StreamPosition)(nil), // 5: controlpb.StreamPosition
	(*FilterNode)(nil),     // 6: controlpb.FilterNode
	(*Unsubscribe)(nil),    // 7: controlpb.Unsubscribe
	(*Disconnect)(nil),     // 8: controlpb.Disconnect
	(*SurveyRequest)(nil),  // 9: controlpb.SurveyRequest
	(*SurveyResponse)(nil), // 10: controlpb.SurveyResponse
	(*Notification)(nil),   // 11: controlpb.Notification
	(*Refresh)(nil),        // 12: controlpb.Refresh
	nil,                    // 13: controlpb.Metrics.ItemsEntry
}
var file_control_proto_depIdxs = []int32{
	2,  // 0: controlpb.Command.node:type_name -> controlpb.Node
	7,  // 1: controlpb.Command.unsubscribe:type_name -> controlpb.Unsubscribe
	8,  // 2: controlpb.Command.disconnect:type_name -> controlpb.Disconnect
	1,  // 3: controlpb.Command.shutdown:type_name -> controlpb.Shutdown
	9,  // 4: controlpb.Command.survey_request:type_name -> controlpb.SurveyRequest
	10, // 5: controlpb.Command.survey_response:type_name -> controlpb.SurveyResponse
	4,  // 6: controlpb.Command.subscribe:type_name -> controlpb.Subscribe
	11, // 7: controlpb.Command.notification:type_name -> controlpb.Notification
	12, // 8: controlpb.Command.refresh:type_name -> controlpb.Refresh
	3,  // 9: controlpb.Node.metrics:type_name -> controlpb.Metrics
	13, // 10: controlpb.Metrics.items:type_name -> controlpb.Metrics.ItemsEntry
	5,  // 11: controlpb.Subscribe.recover_since:type_name -> controlpb.StreamPosition
	6,  // 12: controlpb.Subscribe.label_filter:type_name -> controlpb.FilterNode
	6,  // 13: controlpb.FilterNode.nodes:type_name -> controlpb.FilterNode
	6,  // 14: controlpb.Unsubscribe.label_filter:type_name -> controlpb.FilterNode
	6,  // 15: controlpb.Disconnect.label_filter:type_name -> controlpb.FilterNode
	6,  // 16: controlpb.Refresh.label_filter:type_name -> controlpb.FilterNode
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init()                    { file_control_proto_init() }
func file_control_proto_init() { _ = "STUB: not implemented"; return }
