// Code generated by protoc-gen-go-vtproto. DO NOT EDIT.
// protoc-gen-go-vtproto version: v0.6.0
// source: control.proto

package controlpb

import (
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

func (m *Command) MarshalVT() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Command) MarshalToVT(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Command) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Shutdown) MarshalVT() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Shutdown) MarshalToVT(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Shutdown) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Node) MarshalVT() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Node) MarshalToVT(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Node) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Metrics) MarshalVT() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Metrics) MarshalToVT(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Metrics) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Subscribe) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Subscribe) MarshalToVT(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Subscribe) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StreamPosition) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *StreamPosition) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *StreamPosition) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *FilterNode) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *FilterNode) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *FilterNode) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Unsubscribe) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Unsubscribe) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Unsubscribe) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Disconnect) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Disconnect) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Disconnect) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SurveyRequest) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SurveyRequest) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SurveyRequest) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SurveyResponse) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SurveyResponse) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SurveyResponse) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Notification) MarshalVT() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Notification) MarshalToVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Notification) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Refresh) MarshalVT() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Refresh) MarshalToVT(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Refresh) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Command) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Shutdown) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Node) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Metrics) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Subscribe) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *StreamPosition) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *FilterNode) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Unsubscribe) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Disconnect) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SurveyRequest) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SurveyResponse) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Notification) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Refresh) SizeVT() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Command) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Shutdown) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Node) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Metrics) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Subscribe) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *StreamPosition) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *FilterNode) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Unsubscribe) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Disconnect) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SurveyRequest) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SurveyResponse) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Notification) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Refresh) UnmarshalVT(dAtA []byte) error { _ = "STUB: not implemented"; return nil }
